package com.steven.orm.model;

import java.util.Date;

public class ArthurDemo2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arthur_demo2.BillID
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    private Integer billid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arthur_demo2.Sequence
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arthur_demo2.No
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arthur_demo2.BillDate
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    private Date billdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arthur_demo2.Status
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arthur_demo2.Maker
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    private Integer maker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arthur_demo2.MakeDate
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    private Date makedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arthur_demo2.BillID
     *
     * @return the value of arthur_demo2.BillID
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arthur_demo2.BillID
     *
     * @param billid the value for arthur_demo2.BillID
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arthur_demo2.Sequence
     *
     * @return the value of arthur_demo2.Sequence
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arthur_demo2.Sequence
     *
     * @param sequence the value for arthur_demo2.Sequence
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arthur_demo2.No
     *
     * @return the value of arthur_demo2.No
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arthur_demo2.No
     *
     * @param no the value for arthur_demo2.No
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arthur_demo2.BillDate
     *
     * @return the value of arthur_demo2.BillDate
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public Date getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arthur_demo2.BillDate
     *
     * @param billdate the value for arthur_demo2.BillDate
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public void setBilldate(Date billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arthur_demo2.Status
     *
     * @return the value of arthur_demo2.Status
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arthur_demo2.Status
     *
     * @param status the value for arthur_demo2.Status
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arthur_demo2.Maker
     *
     * @return the value of arthur_demo2.Maker
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public Integer getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arthur_demo2.Maker
     *
     * @param maker the value for arthur_demo2.Maker
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public void setMaker(Integer maker) {
        this.maker = maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arthur_demo2.MakeDate
     *
     * @return the value of arthur_demo2.MakeDate
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arthur_demo2.MakeDate
     *
     * @param makedate the value for arthur_demo2.MakeDate
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }
}