package com.steven.orm.client;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.steven.orm.model.ArthurDemo2;
import com.steven.orm.model.ArthurDemo2Example;
public interface ArthurDemo2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    long countByExample(ArthurDemo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int deleteByExample(ArthurDemo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int deleteByPrimaryKey(Integer billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int insert(ArthurDemo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int insertSelective(ArthurDemo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    List<ArthurDemo2> selectByExample(ArthurDemo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    ArthurDemo2 selectByPrimaryKey(Integer billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") ArthurDemo2 record, @Param("example") ArthurDemo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int updateByExample(@Param("record") ArthurDemo2 record, @Param("example") ArthurDemo2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int updateByPrimaryKeySelective(ArthurDemo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arthur_demo2
     *
     * @mbg.generated Wed Mar 08 13:11:25 CST 2017
     */
    int updateByPrimaryKey(ArthurDemo2 record);
}